/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_A403E530__
#define __PLUGINEDITOR_H_A403E530__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class Key_valueAudioProcessorEditor  : public AudioProcessorEditor,
                                       public ComboBox::Listener,
                                       public Button::Listener
{
public:
    Key_valueAudioProcessorEditor (Key_valueAudioProcessor* ownerFilter);
    ~Key_valueAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    
    void resized();
    
    /** Called when the combobox is changed. */
    void comboBoxChanged (ComboBox *comboBoxThatHasChanged);
    
    /** Called when the button is clicked. */
    void buttonClicked (Button* button);
    
private:
    
    ComboBox    performerMidiInputSelectorA, performerMidiInputSelectorB, mode;
    Label       performerMidiInputSelectorALabel, performerMidiInputSelectorBLabel, modeLabel;
        
    TextButton  connectToIPC;
        
    Key_valueAudioProcessor* getProcessor() const throw()       
    { 
        return (Key_valueAudioProcessor*) getAudioProcessor(); 
    }
};


#endif  // __PLUGINEDITOR_H_A403E530__
